"""Inbound model: Add 3 fields for xray

Revision ID: 2d064a07c9e0
Revises: 4f9a47e022a1
Create Date: 2026-05-13 20:18:38.988481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d064a07c9e0'
down_revision: Union[str, Sequence[str], None] = '4f9a47e022a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbounds', sa.Column('reality_private_key', sa.String(length=64), nullable=True))
    op.add_column('inbounds', sa.Column('reality_public_key', sa.String(length=64), nullable=True))
    op.add_column('inbounds', sa.Column('reality_short_id', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbounds', 'reality_short_id')
    op.drop_column('inbounds', 'reality_public_key')
    op.drop_column('inbounds', 'reality_private_key')
    # ### end Alembic commands ###
