"""add tag to inbound

Revision ID: 444378c09f78
Revises: 2d064a07c9e0
Create Date: 2026-05-14 16:27:08.997882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444378c09f78'
down_revision: Union[str, Sequence[str], None] = '2d064a07c9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbounds', sa.Column('tag', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbounds', 'tag')
    # ### end Alembic commands ###
