"""Change db shemas and links

Revision ID: 4f9a47e022a1
Revises: c3bed8abbcab
Create Date: 2026-05-13 16:30:29.683775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f9a47e022a1'
down_revision: Union[str, Sequence[str], None] = 'c3bed8abbcab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xray_uuid', sa.String(length=36), nullable=False),
    sa.Column('hysteria2_password', sa.String(length=128), nullable=False),
    sa.Column('naiveproxy_username', sa.String(length=64), nullable=False),
    sa.Column('naiveproxy_password', sa.String(length=128), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.add_column('subscriptions', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'is_active')
    op.drop_table('client_credentials')
    # ### end Alembic commands ###
